#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for pool
#
#  Portions Copyright (c) 2010 Nippon Telegraph and Telephone Corporation
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/pool
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = datanode.o execRemote.o poolmgr.o poolcomm.o

include $(top_srcdir)/src/backend/common.mk
