#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator
#
# Copyright (c) 2010-2013, Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/locator
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = locator.o

include $(top_srcdir)/src/backend/common.mk
