#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for locator
#
#
# Copyright(C) 2010 Nippon Telegraph and Telephone Corporation
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/locator
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = locator.o

include $(top_srcdir)/src/backend/common.mk
