#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for rewrite
#
# Portions Copyright (c) 2010-2013, Postgres-XC Development Group
#
# IDENTIFICATION
#    $PostgreSQL$
#
#-------------------------------------------------------------------------

subdir = src/backend/pgxc/plan
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = planner.o

include $(top_srcdir)/src/backend/common.mk
