#
# Makefile for the access methods module
#
#
# Portions Copyright (c) 2010-2011 Nippon Telegraph and Telephone Corporation
#
# $PostgreSQL$
#

subdir = src/backend/pgxc
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = locator plan pool barrier

include $(top_srcdir)/src/backend/common.mk
