#----------------------------------------------------------------------------
#
# Postgres-XC backend method makefile
#
# Copyright(c) 2010-2012 Postgres-XC Development Group
#
# src/backend/pgxc/Makefile
#
#-----------------------------------------------------------------------------
subdir = src/backend/pgxc
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS	    = locator plan pool barrier nodemgr xc_maintenance_mode

include $(top_srcdir)/src/backend/common.mk
