#----------------------------------------------------------------------------
#
# Postgres-XC documentation tool makefile
#
# Copyright (c) 2010-2012 Nippon Telegraph and Telephone Corporation
#
# doc-xc/Makefile
#
#----------------------------------------------------------------------------

subdir = src/pgxc
top_builddir = ../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = bin tools

$(recurse)
